Repository UXCorpRangel/js-conf-cl-2024, pull requests merged in 2024-10, with the labels that each got.

#94 docs: :memo: update readme
  README.md
Labels: documentation

#97 feat: :sparkles: add new communities to Slider component
  public/assets/img/communities/AngularPeru.avif
  public/assets/img/communities/DevsChile.avif
  public/assets/img/communities/cloudclubchile.avif
  public/assets/img/communities/python.avif
  src/components/Slider/Slider.astro
  src/components/Slider/data.ts
Labels: enhancement

#98 feat: :sparkles: add footer links and change logo component
  src/components/Footer/Footer.astro
  src/components/Footer/JSConf2024.astro
  src/components/Footer/data.ts
  src/icons/JsConfCl.svg
Labels: enhancement

#100 feat: :sparkles: add sponsor details page
  apps/jsconf/public/assets/img/sponsors/sponsor-detail-placeholder.avif
  apps/jsconf/src/data/sponsors/sponsors.json
  apps/jsconf/src/pages/sponsors/[sponsors].astro
  apps/jsconf/src/pages/sponsors/index.astro
Labels: enhancement

#102 feat: :busts_in_silhouette: update staff and volunteer
  apps/jsconf/public/assets/img/volunteer/samuel-llibre-pillco.avif
  apps/jsconf/src/sections/Staff/data.ts
  apps/jsconf/src/sections/Volunteer/data.ts
  apps/previa/src/sections/Staff/data.ts
Labels: enhancement

#103 feat: :busts_in_silhouette: add Mermelada Tech community
  apps/jsconf/public/assets/img/communities/mermelada-tech.avif
  apps/jsconf/src/components/Slider/data.ts
Labels: enhancement

#105 feat: :lipstick: add gradients to `Slider` component
  apps/jsconf/src/components/Slider/Slider.astro
  apps/previa/src/components/Slider/Slider.astro
Labels: enhancement

#104 fix: :lipstick: change some style properties
  apps/jsconf/src/components/Footer/Footer.astro
  apps/previa/src/components/Footer/Footer.astro
Labels: enhancement

#106 fix: :lipstick: change responsive styles
  apps/jsconf/src/sections/Views.astro
  apps/previa/src/components/SpeakerCard.astro
  apps/previa/src/sections/Speakers.astro
  apps/previa/src/sections/Sponsors.astro
  apps/previa/src/sections/Views.astro
Labels: bug

#107 feat: :busts_in_silhouette: add ux friends community
  apps/jsconf/public/assets/img/communities/ux-friends.avif
  apps/jsconf/src/components/Slider/data.ts
  apps/previa/public/assets/img/communities/ux-friends.avif
  apps/previa/src/components/Slider/data.ts
Labels: enhancement

#108 fix: :lipstick: change the order of the footer items
  apps/jsconf/src/components/Footer/Footer.astro
  apps/previa/src/components/Footer/Footer.astro
Labels: enhancement

#128 fix: :lipstick: improve styles for responsive view
  apps/jsconf/public/assets/img/JSConf-Chile-charlista.webp
  apps/jsconf/public/assets/img/JSConf-Chile-entrada.webp
  apps/jsconf/public/assets/img/JSConf-Chile-publico.webp
  apps/jsconf/src/components/Bento.astro
  apps/jsconf/src/pages/por-que.astro
Labels: enhancement

#129 fix: :lipstick: improve responsive design
  apps/jsconf/src/components/EventCard.astro
  apps/jsconf/src/pages/charlistas/[charlistas].astro
Labels: enhancement

#130 fix: :sparkles: add opacity to hero caption image
  apps/jsconf/src/components/DateInfoHome.astro
  apps/jsconf/src/sections/Hero.astro
Labels: enhancement

#133 fix: :ambulance: add missing community and remove unused script
  apps/jsconf/src/components/Slider/Slider.astro
  apps/jsconf/src/components/Slider/data.ts
  apps/previa/src/components/Slider/Slider.astro
  apps/previa/src/components/Slider/data.ts
  apps/previa/src/sections/Speakers.astro
Labels: bug

#141 feat: :busts_in_silhouette: add sponsor: cloudflare
  apps/jsconf/public/assets/img/sponsors/Cloudflare-Logo.webp
  apps/jsconf/src/sections/Sponsors.astro
Labels: enhancement

#142 Feat/speakers card update
  apps/jsconf/public/assets/img/speakers/angel-bulnes/angel-bulnes-5.webp
  apps/jsconf/public/assets/img/speakers/boris-belmar/boris-belmar-5.webp
  apps/jsconf/public/assets/img/speakers/erick-wendel/erick-wendel-1.webp
  apps/jsconf/public/assets/img/speakers/erick-wendel/erick-wendel-2.webp
  apps/jsconf/public/assets/img/speakers/erick-wendel/erick-wendel-3.webp
  apps/jsconf/public/assets/img/speakers/erick-wendel/erick-wendel-4.webp
  apps/jsconf/public/assets/img/speakers/estefany-aguilar-restrepo/estefany-aguilar-restrepo-1.webp
  apps/jsconf/public/assets/img/speakers/estefany-aguilar-restrepo/estefany-aguilar-restrepo-2.webp
  apps/jsconf/public/assets/img/speakers/estefany-aguilar-restrepo/estefany-aguilar-restrepo-3.webp
  apps/jsconf/public/assets/img/speakers/estefany-aguilar-restrepo/estefany-aguilar-restrepo-4.webp
  apps/jsconf/public/assets/img/speakers/estefany-aguilar-restrepo/estefany-aguilar-restrepo-5.webp
  apps/jsconf/public/assets/img/speakers/francisca-beatriz-medina-concha/francisca-beatriz-medina-concha-5.webp
  apps/jsconf/public/assets/img/speakers/ignacio-anaya/ignacio-anaya-5.webp
  apps/jsconf/public/assets/img/speakers/jo-franchetti/jo-franchetti-5.webp
  apps/jsconf/public/assets/img/speakers/marian-villa/marian-villa-1.webp
  apps/jsconf/public/assets/img/speakers/marian-villa/marian-villa-2.webp
  apps/jsconf/public/assets/img/speakers/marian-villa/marian-villa-3.webp
  apps/jsconf/public/assets/img/speakers/marian-villa/marian-villa-4.webp
  apps/jsconf/public/assets/img/speakers/rita-kozlov/rita-kozlov-1.webp
  apps/jsconf/src/components/SpeakerCard.astro
  apps/jsconf/src/data/speakers/charlistas.json
  apps/jsconf/src/pages/charlistas/[charlistas].astro
  apps/jsconf/src/pages/charlistas/index.astro
  apps/jsconf/src/sections/charlistas/SpeakersTab.astro
Labels: enhancement

#143 Feat/agenda
  apps/jsconf/src/components/Navbar/data.ts
  apps/jsconf/src/components/TabsSchedule.astro
  apps/jsconf/src/data/agenda/agenda.ts
  apps/jsconf/src/pages/agenda.astro
  apps/jsconf/src/pages/charlistas/index.astro
  apps/jsconf/src/pages/index.astro
  apps/jsconf/src/sections/Speakers.astro
  apps/jsconf/src/sections/agenda/ContentTab.astro
Labels: enhancement
